### PR TITLE
First build and test run of program_options

### PR DESCRIPTION
**Pull request by andrewkatson**
This has all tests passing. Didn't bother with the cfg or python tests

### CODE REVIEW

**Comment by andrewkatson** [comment]
@zaucy  have you seen this error. I have seen it with my Windows build of my personal project but I have never fixed it before. 

```
ERROR: D:/a/program_options/program_options/test/BUILD.bazel:20:9: Linking optional_test.exe failed: (Exit 1104): link.exe failed: error executing CppLink command (from target //:optional_test) C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.39.33519\bin\HostX64\x64\link.exe @bazel-out/x64_windows-fastbuild/bin/optional_test.exe-2.params
LINK : fatal error LNK1104: cannot open file 'libboost_program_options-vc143-mt-x64-1_83.lib'
```

**Comment by zaucy** [comment]
Yea that's boosts "auto-linking" feature. Not very useful for bazel projects. All you gotta do is add `BOOST_ALL_NO_LIB` to the boost target (`//:program_options`) to disable it. e.g. https://github.com/bazelboost/filesystem/blob/bazelboost-1.83.0/BUILD.bazel#L16

**Comment by andrewkatson** [comment]
How did you figure that out?

**Comment by zaucy** [comment]
just by knowing about the auto linking feature. I started using boost 10 years ago and I had to deal with it plenty when compiling boost on Windows. You _may_ see it on other C++ projects that use msvc if you ever see this:

```cpp
#pragma comment(lib, "some_library_you_want_to_link")
```

references:

* https://learn.microsoft.com/en-us/cpp/preprocessor/comment-c-cpp?view=msvc-170#examples
* https://www.boost.org/doc/libs/1_85_0/more/getting_started/windows.html#auto-linking
* https://www.boost.org/doc/libs/1_81_0/boost/config/auto_link.hpp

**Review by zaucy — APPROVED** [review]
LGTM! Thanks for getting this up and running!

**Comment by andrewkatson** [comment]
Thank you for explaining that! That will definitely help. I love learning new things. Let me know when it is merged so I can start on the next one.

**Comment by zaucy** [comment]
released! `1.83.0.bzl.2` should be in the registry!

**Pull request merged**
